remote_theme: coursweb/jk-theme
title: Association NDZOUANA
description: Description de cet exemple

lang: fr-FR

robots: noindex, nofollow

# menu
chapters:
 - title: Cours-Web 
   url: https://cours-web.ch/
 - title: MDN
   url: https://developer.mozilla.org/fr/

# pied de page
footer_col_1: <ul class="contact-list">
  <li> Association Ndzouana</li>
  <li>13 rue de la Tour</li>
  <li>95120 - Ermont</li>
  <li>---</li>
  <li>[ndzouana@outlook.com](ndzouana@outlook.com)</li>
  <li>2025</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/">Lien Github</a></li></ul>
